apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.resourcePrefix }}-deployment
  labels:
    app: &app {{.Values.resourcePrefix}}-{{.Release.Name}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      labels:
        app: *app
    spec:
      containers:
        - name: *app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command:
            - redis-server
            - {{ .Values.conf.dir }}{{ .Values.conf.path }}
          ports:
            - containerPort: {{ .Values.port }}
              name: {{ .Release.Name }}
          volumeMounts:
            - name: &confname {{ .Release.Name }}-{{ .Values.resourcePrefix }}-{{.Values.conf.name }}
              mountPath: {{ .Values.conf.dir }}
      volumes:
        - name: *confname
          configMap:
            name: *confname
            items:
            - key: *confname
              path: {{ .Values.conf.path }}
