run:
  timeout: 10m
  skip-dirs:
    - pkg/util/emoji
    - pkg/util/route
linters:
  disable-all: true
  enable:
    # UNUSED
    - deadcode
    - varcheck
    - unused
    - structcheck
    - ineffassign
    - unparam
    # STYLE
    - gosimple
    - godot
    - dogsled
    - gochecknoinits
    # BUGS
    - errcheck
    - govet
    - staticcheck
    - nilerr
    # Disabling for now due to generics issues
#    - typecheck
    # COMPLEXITY
    - gocognit
    # TEST
    - testpackage