version: "3.9"
services:
  arya-core:
    build: ../
    ports:
      - 8080:8080
    env_file:
      - ./dev.env
    depends_on:
      - arya-db
    volumes:
      - ../:/arya-core
    stdin_open: true
    tty: true
  arya-db:
    image: postgres:latest
    ports:
      - 5102:5432
    environment:
      - POSTGRES_USER=${ARYA_DB_USER}
      - POSTGRES_DB=${ARYA_DB_NAME}
      - POSTGRES_PASSWORD=${ARYA_DB_PASSWORD}
    volumes:
      - arya-data:/var/lib/postgresql/data
volumes:
  arya-data:



