{
 "title": "Arya Core",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Ingestion Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node_1_stats\" or r[\"_measurement\"] == \"node_2_stats\" or r[\"_measurement\"] == \"node_3_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sample/s\")\n  |> aggregateWindow(every: 30s, fn: max, createEmpty: false)\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Active Processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node_1_stats\" or r[\"_measurement\"] == \"node_2_stats\" or r[\"_measurement\"] == \"node_3_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"num_go_routine\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"default\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node_1_stats\" or r[\"_measurement\"] == \"node_2_stats\" or r[\"_measurement\"] == \"node_3_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"mem_usage\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}