// Code generated by "stringer -type=OverlapType"; DO NOT EDIT.

package telem

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OverlapTypeNoneOrInvalid-0]
	_ = x[OverlapTypeRightPartial-1]
	_ = x[OverlapTypeLeftPartial-2]
	_ = x[OverlapTypeSourceConsume-3]
	_ = x[OverlapTypeDestConsume-4]
	_ = x[OverlapTypeDuplicate-5]
}

const _OverlapType_name = "OverlapTypeNoneOrInvalidOverlapTypeRightPartialOverlapTypeLeftPartialOverlapTypeSourceConsumeOverlapTypeDestConsumeOverlapTypeDuplicate"

var _OverlapType_index = [...]uint8{0, 24, 47, 69, 93, 115, 135}

func (i OverlapType) String() string {
	if i < 0 || i >= OverlapType(len(_OverlapType_index)-1) {
		return "OverlapType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OverlapType_name[_OverlapType_index[i]:_OverlapType_index[i+1]]
}
