// Code generated by "stringer -type=Calc"; DO NOT EDIT.

package query

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CalcSum-0]
	_ = x[CalcMax-1]
	_ = x[CalcMin-2]
	_ = x[CalcCount-3]
	_ = x[CalcAVG-4]
}

const _Calc_name = "CalcSumCalcMaxCalcMinCalcCountCalcAVG"

var _Calc_index = [...]uint8{0, 7, 14, 21, 30, 37}

func (i Calc) String() string {
	if i < 0 || i >= Calc(len(_Calc_index)-1) {
		return "Calc(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Calc_name[_Calc_index[i]:_Calc_index[i+1]]
}
