// Code generated by "stringer -type=FieldOp"; DO NOT EDIT.

package query

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FieldOpGreaterThan-0]
	_ = x[FieldOpLessThan-1]
	_ = x[FieldOpInRange-2]
	_ = x[FieldOpIn-3]
}

const _FieldOp_name = "FieldOpGreaterThanFieldOpLessThanFieldOpInRangeFieldOpIn"

var _FieldOp_index = [...]uint8{0, 18, 33, 47, 56}

func (i FieldOp) String() string {
	if i < 0 || i >= FieldOp(len(_FieldOp_index)-1) {
		return "FieldOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FieldOp_name[_FieldOp_index[i]:_FieldOp_index[i+1]]
}
