// Code generated by "stringer -type=ChannelState"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ChannelStatusInactive-1]
	_ = x[ChannelStatusActive-2]
}

const _ChannelState_name = "ChannelStateInactiveChannelStateActive"

var _ChannelState_index = [...]uint8{0, 20, 38}

func (i ChannelState) String() string {
	i -= 1
	if i < 0 || i >= ChannelState(len(_ChannelState_index)-1) {
		return "ChannelState(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ChannelState_name[_ChannelState_index[i]:_ChannelState_index[i+1]]
}
