// Code generated by "stringer -type=ChannelConflictPolicy"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ChannelConflictPolicyError-0]
	_ = x[ChannelConflictPolicyDiscard-1]
	_ = x[ChannelConflictPolicyOverwrite-2]
}

const _ChannelConflictPolicy_name = "ChannelConflictPolicyErrorChannelConflictPolicyDiscardChannelConflictPolicyOverwrite"

var _ChannelConflictPolicy_index = [...]uint8{0, 26, 54, 84}

func (i ChannelConflictPolicy) String() string {
	if i < 0 || i >= ChannelConflictPolicy(len(_ChannelConflictPolicy_index)-1) {
		return "ChannelConflictPolicy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChannelConflictPolicy_name[_ChannelConflictPolicy_index[i]:_ChannelConflictPolicy_index[i+1]]
}
