auth:
  username: &username arya-master
  password: &password arya-dummy-pass
redistimeseries:
  auth:
    username: *username
    password: *password
cockroachdb:
  join: 192.168.64.12,192.168.64.13
