resourcePrefix: aryacore
image:
  repository: ghcr.io/arya-analytics/arya-core
  tag: bcc0b66-dirty
  pullPolicy: Always
auth:
  username: &username arya-master
  password: &password arya-dummy-pass
redistimeseries:
  auth:
    username: *username
    password: *password
cockroachdb:
  join: 192.168.64.12,192.168.64.13
imagePullSecrets:
  name: regcred
