// Code generated by "stringer -type=ErrorType"; DO NOT EDIT.

package storage

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrTypeUnknown-0]
	_ = x[ErrTypeItemNotFound-1]
	_ = x[ErrTypeUniqueViolation-2]
	_ = x[ErrTypeRelationshipViolation-3]
	_ = x[ErrTypeInvalidField-4]
	_ = x[ErrTypeNoPK-5]
	_ = x[ErrTypeMigration-6]
	_ = x[ErrTypeInvalidArgs-7]
}

const _ErrorType_name = "ErrTypeUnknownErrTypeItemNotFoundErrTypeUniqueViolationErrTypeRelationshipViolationErrTypeInvalidFieldErrTypeNoPKErrTypeMigrationErrTypeInvalidArgs"

var _ErrorType_index = [...]uint8{0, 14, 33, 55, 83, 102, 113, 129, 147}

func (i ErrorType) String() string {
	if i < 0 || i >= ErrorType(len(_ErrorType_index)-1) {
		return "ErrorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorType_name[_ErrorType_index[i]:_ErrorType_index[i+1]]
}
