// Code generated by "stringer -type=ErrorType"; DO NOT EDIT.

package storage

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorTypeUnknown-0]
	_ = x[ErrorTypeItemNotFound-1]
	_ = x[ErrorTypeUniqueViolation-2]
	_ = x[ErrorTypeRelationshipViolation-3]
	_ = x[ErrorTypeInvalidField-4]
	_ = x[ErrorTypeNoPK-5]
	_ = x[ErrorTypeMigration-6]
	_ = x[ErrorTypeInvalidArgs-7]
	_ = x[ErrorTypeConnection-8]
}

const _ErrorType_name = "ErrorTypeUnknownErrorTypeItemNotFoundErrorTypeUniqueViolationErrorTypeRelationshipViolationErrorTypeInvalidFieldErrorTypeNoPKErrorTypeMigrationErrorTypeInvalidArgsErrorTypeConnection"

var _ErrorType_index = [...]uint8{0, 16, 37, 61, 91, 112, 125, 143, 163, 182}

func (i ErrorType) String() string {
	if i < 0 || i >= ErrorType(len(_ErrorType_index)-1) {
		return "ErrorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorType_name[_ErrorType_index[i]:_ErrorType_index[i+1]]
}
