resourcePrefix: arya-core
image:
  repository: ghcr.io/arya-analytics/arya-core
  tag: bcc0b66-dirty
  pullPolicy: Always
auth:
  username: &username arya-master
  password: &password arya-dummy-pass
redistimeseries:
  auth:
    username: *username
    password: *password
minio:
  auth:
    accessKey: *username
    secretKey: *password
cockroachdb:
  join: 192.168.64.11
imagePullSecrets:
  name: regcred
