apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.resourcePrefix }}-service
  labels:
    app: &app {{.Release.Name }}-{{ .Values.resourcePrefix }}
spec:
  ports:
    - port: {{.Values.ports.grpc}}
      name: grpc
    - port: {{.Values.ports.http}}
      name: http
  selector:
    app: *app
