resourcePrefix: minio
image:
  repository: minio/minio
  tag: RELEASE.2021-11-24T23-19-33Z
  pullPolicy: IfNotPresent
hostNetwork: true
ports:
  http: 9000
  console: 9001
volumes:
  name: data
  containerPath: /minio/minio-data
  hostPath: /minio/minio-data
auth:
  accessKey: arya-master
  secretKey: arya-dummy-pass