// Code generated by "stringer -type=QueryVariant"; DO NOT EDIT.

package internal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[QueryVariantCreate-0]
	_ = x[QueryVariantRetrieve-1]
	_ = x[QueryVariantUpdate-2]
	_ = x[QueryVariantDelete-3]
}

const _QueryVariant_name = "QueryVariantCreateQueryVariantRetrieveQueryVariantUpdateQueryVariantDelete"

var _QueryVariant_index = [...]uint8{0, 18, 38, 56, 74}

func (i QueryVariant) String() string {
	if i < 0 || i >= QueryVariant(len(_QueryVariant_index)-1) {
		return "QueryVariant(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _QueryVariant_name[_QueryVariant_index[i]:_QueryVariant_index[i+1]]
}
