name: Buf Push
on:
  push:
    branches:
      - main
jobs:
  buf-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v0.6.0
      - name: Buf Login
        run: echo ${{ secrets.BUF_TOKEN }} | buf registry login --username=emilbon99 --token-stdin
      - name: Buf Push Cluster
        working-directory: pkg/cluster
        run: buf mod update && buf build && buf generate && buf push
      - name: Buf Push API
        working-directory: pkg/api/rpc
        run: buf mod update && buf build && buf generate && buf push



