name: Go

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Setup Tests
      run: |
        go get github.com/onsi/ginkgo/v2/ginkgo/generators@v2.0.0
        go get github.com/onsi/ginkgo/v2/ginkgo/internal@v2.0.0
        go get github.com/onsi/ginkgo/v2/ginkgo/labels@v2.0.0
        go install github.com/onsi/ginkgo/v2/ginkgo
    - name: Test
      run: ginkgo -r --skip-package=dev
