name: Test

on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redistimeseries:
        image: redislabs/redistimeseries
        ports:
          - 6379:6379
      minio:
        image: mosuka/minio:latest
        ports:
          - "9000:9000"
          - "9001:9001"
        env:
          MINIO_ROOT_USER: minio
          MINIO_ROOT_PASSWORD: minio123
    steps:
      - name: Cache bazelisk
        uses: actions/cache@v2
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-development

      - uses: actions/checkout@v2

      - name: Build
        run: bazel build //...

      - name: Test
        run: bazel coverage //... --test_output=errors

      - name: Upload Coverage
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

