name: Test

on: [ push, pull_request ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redistimeseries:
        image: redislabs/redistimeseries
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v2

      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Set Up Tests
        run: |
          go get github.com/onsi/ginkgo/v2/ginkgo/generators@v2.0.0
          go get github.com/onsi/ginkgo/v2/ginkgo/internal@v2.0.0
          go get github.com/onsi/ginkgo/v2/ginkgo/labels@v2.0.0
          go install github.com/onsi/ginkgo/v2/ginkgo

      - name: Run Tests
        run: ginkgo -r --covermode=atomic --coverprofile=coverage.txt -covermode=atomic
          --skip-package=dev

      - name: Upload Coverage
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

